### ISSUE TITLE
[readme] Didnt found exemple code for Planetception

### ISSUE THREAD

**Issue by c0ncentus** [innFactory/react-planet#5]
hi,

the link on the readme :
https://github.com/innFactory/react-planet/blob/master/src/stories/Planet.stories.tsx

Current behaviour:
![image](https://user-images.githubusercontent.com/25374826/101386275-3ee37300-38bd-11eb-827c-2e8750fae21e.png)

Excpected behaviour : have a link  to see the code please 👍

**Comment by spoeck** [comment]
Thank you. The link is: https://github.com/innFactory/react-planet/blob/master/src/stories/Planetception.stories.tsx
It's fixed in the readme.
